development: &devconf
    bind_master_host:       '127.0.0.1'
    bind_master_port:       5353
    bind_slave_host:        '127.0.0.1'
    bind_slave_port:        5354
    bind_user:              'bind'
    bind_group:             'bind'
    bind_config_file:       '/etc/named.conf'
    bind_config_dir:        '/etc/named/'
    bind_master_chroot_dir: '/var/named/chroot_master/'
    bind_slave_chroot_dir:  '/var/named/chroot_slave/'
    bind_error_log:         '/var/named/chroot_master/var/log/globodns.error.log'

    rndc_config_file:       '/etc/rndc.conf'
    rndc_key:               'rndc-key'

    named_conf_file:        'named.conf'
    zones_dir:              'zones'
    zones_file:             'zones.conf'
    reverse_dir:            'reverse'
    reverse_file:           'reverse.conf'
    slaves_dir:             'slaves'
    slaves_file:            'slaves.conf'
    views_file:             'views.conf'

    nameserver_host:        'localhost'
    record_order:           [ SOA, NS, MX, A, AAAA, CNAME, LOC, SPF, SRV, PTR, TXT ]

    binaries:
        bind:          '/usr/sbin/named'
        named:         '/usr/sbin/named'
        rndc:          '/usr/sbin/rndc'
        rndc_confgen:  '/usr/sbin/rndc-confgen'
        checkconf:     '/usr/sbin/named-checkconf'
        dig:           '/usr/bin/dig'
        git:           '/usr/bin/git'
        zone2sql:      '/usr/bin/zone2sql'
        rsync:         '/usr/bin/rsync'
        sudo:          '/usr/bin/sudo'
        chroot:        '/usr/sbin/chroot'

test:
    bind_user:         <%= ENV['USER'] %>
    bind_group:        'bind'
    bind_master_host:  '127.0.0.1'
    bind_master_port:  5353
    bind_slave_host:   '127.0.0.1'
    bind_slave_port:   5354
    bind_config_file:  '/etc/named.conf'
    bind_config_dir:   '/etc/named/'
    bind_error_log:    '/var/log/globodns.error.log'
    bind_chroot_dir:   <%= Rails.root.join('test', 'mock', 'named_chroot') %>
    rndc_config_file:  <%= Rails.root.join('test', 'mock', 'named_chroot', 'etc', 'rndc.conf') %>
    rndc_key:          'rndc-key'
    named_conf_file:   'named.conf'
    zones_dir:         'zones'
    zones_file:        'zones.conf'
    reverse_dir:       'reverse'
    reverse_file:      'reverse.conf'
    slaves_dir:        'slaves'
    slaves_file:       'slaves.conf'
    views_file:        'views.conf'
    nameserver_host:   'localhost'
    record_order:      [ SOA, NS, MX, A, AAAA, CNAME, LOC, SPF, SRV, PTR, TXT ]
    binaries:
        bind:          '/usr/sbin/named'
        named:         '/usr/sbin/named'
        rndc:          '/usr/sbin/rndc'
        checkconf:     '/usr/sbin/named-checkconf'
        git:           '/usr/bin/git'
        zone2sql:      '/usr/bin/zone2sql'
        rsync:         '/usr/bin/rsync'
        sudo:          '/usr/bin/sudo'
        chroot:        '/usr/sbin/chroot'

production: *devconf

