default: &default
  oauth_provider_client_id: <%= ENV["OAUTH_PVDR_CLID"] %>
  oauth_provider_client_secret: <%= ENV["OAUTH_PVDR_CLSC"] %>

development:
  <<: *default
  secret_key_base: ENV["SECRET_KEY_BASE"]

dev:
  <<: *default
  secret_key_base: ENV["SECRET_KEY_BASE"]

qa:
  <<: *default

production:
  <<: *default