default: &default
  accounts_backstage_client_id: <%= ENV["ACC_BKST_CLID"] %>
  accounts_backstage_client_secret: <%= ENV["ACC_BKST_CLSC"] %>

development:
  <<: *default
  secret_key_base: ENV["SECRET_KEY_BASE"]

dev:
  <<: *default
  secret_key_base: ENV["SECRET_KEY_BASE"]

qa:
  <<: *default

production:
  <<: *default